@startuml s2s-oauth

!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Web/AzureAPIManagement.puml
!includeurl AzurePuml/Compute/AzureFunction.puml

LAYOUT_LEFT_RIGHT

title Service-to-Service Authorization (OAuth)

AzureActiveDirectory(aad, "OAuth", "API scopes and authorizations")
AzureAPIManagement(apim, "apim01", "Managed Identity / Client Certificate", "Validate OAuth tokens and perform access control checks.")
AzureFunction(func1, "Delivery", "Managed Identity", "<color:red>Only acccept proxied APIM connections")
AzureFunction(func2, "Orders", "Managed Identity", "<color:red>Only acccept proxied APIM connections")

Rel(func1, aad, "1. Request Access Token\nManaged Identity\nResource: api://orders")
Rel_Back(func1, aad, "2. Access Token\naud:api://orders\nroles: [orders.read]")
Rel(func1, apim, "3. Request order status\nAccess Token")
Rel(apim, aad, "4. Validate token")
Rel_Back(func2, apim, "5. Proxied call\nAPIM client cert\nor\nAPIM Managed Instance token")

@end